<a href="https://colab.research.google.com/github/siddheshpednekar/bdapracticals_sem3/blob/main/P5statistics%26pipeline.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
from pyspark.mllib.stat import Statistics
mat = sc.parallelize([np.array([1.0, 10.0, 100.0]), np.array([2.0, 20.0, 200.0]), np.array([3.0, 30.0, 300.0])])  

In [ ]:
mat.collect()

Out[7]: [array([  1.,  10., 100.]),
 array([  2.,  20., 200.]),
 array([  3.,  30., 300.])]

In [ ]:
# Compute column summary statistics.
summary = Statistics.colStats(mat)
print(summary.mean())  # a dense vector containing the mean value for each column
print(summary.variance())  # column-wise variance
print(summary.numNonzeros()) 

[  2.  20. 200.]
[1.e+00 1.e+02 1.e+04]
[3. 3. 3.]


In [ ]:
#II Co relation
from pyspark.mllib.stat import Statistics
s1 = sc.parallelize([5,7,9,3,3,2])
s2 = sc.parallelize([55,70,99,33,33,22])
print('Corr between two series is :' + str(Statistics.corr(s1, s2, method="pearson")))

Corr between two series is :0.9958380929519272


In [ ]:
data  = sc.parallelize([np.array([1.0,10.0,100.0]),
                       np.array([2.0,20.0,200.0]),
                       np.array([3.0,30.0,300.0])])
data.collect()

print(Statistics.corr(data,method = 'spearman'))

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
  # Stratified Sampling : it generates randomly sampled data.
data =  sc.parallelize([(1,'a'),(1,'b'),(2,'c'),(2,'d'),(2,'e'),(3,'f'),(3,'g')])    
 # specify the exact fraction desired from each key as a dictionary
fractions = {1: 0.2, 2: 0.6, 3: 0.3}
sample = data.sampleByKey(False,fractions)
sample.collect()

Out[32]: [(1, 'a'), (2, 'd'), (3, 'f')]

In [ ]:
# Hypothesis 
from pyspark.mllib.stat import Statistics
from pyspark.mllib.regression import LabeledPoint
from pyspark.mllib.linalg import Vectors ,Matrices

vec = Vectors.dense(0.1, 0.15, 0.2, 0.3, 0.25)
gof = Statistics.chiSqTest(vec)

print(gof)


mat = Matrices.dense(3,2,[1.0, 3.0, 5.0, 2.0, 4.0, 6.0])
print(mat)

independenceTestResult = Statistics.chiSqTest(mat)

Chi squared test summary:
method: pearson
degrees of freedom = 4 
statistic = 0.12499999999999999 
pValue = 0.998126379239318 
No presumption against null hypothesis: observed follows the same distribution as expected..
DenseMatrix([[1., 2.],
             [3., 4.],
             [5., 6.]])


In [ ]:
print(independenceTestResult)

Chi squared test summary:
method: pearson
degrees of freedom = 2 
statistic = 0.14141414141414144 
pValue = 0.931734784568187 
No presumption against null hypothesis: the occurrence of the outcomes is statistically independent..


In [ ]:
obs = sc.parallelize(
    [LabeledPoint(1.0, [1.0, 0.0, 3.0]),
     LabeledPoint(1.0, [1.0, 2.0, 0.0]),
     LabeledPoint(1.0, [-1.0, 0.0, -0.5])])
    
    # The contingency table is constructed from an RDD of LabeledPoint and used to conduct
# the independence test. Returns an array containing the ChiSquaredTestResult for every feature
# against the label.
featureTestResults = Statistics.chiSqTest(obs)

for i, result in enumerate(featureTestResults):
    print("Column %d:\n%s" % (i + 1, result))

Column 1:
Chi squared test summary:
method: pearson
degrees of freedom = 0 
statistic = 0.0 
pValue = 1.0 
No presumption against null hypothesis: the occurrence of the outcomes is statistically independent..
Column 2:
Chi squared test summary:
method: pearson
degrees of freedom = 0 
statistic = 0.0 
pValue = 1.0 
No presumption against null hypothesis: the occurrence of the outcomes is statistically independent..
Column 3:
Chi squared test summary:
method: pearson
degrees of freedom = 0 
statistic = 0.0 
pValue = 1.0 
No presumption against null hypothesis: the occurrence of the outcomes is statistically independent..


In [ ]:
from pyspark.sql import SparkSession
spark = SparkSession.builder.appName("ChiSquareTestExample").getOrCreate()


In [ ]:
from pyspark.ml.stat import ChiSquareTest
from pyspark.ml.linalg import Vectors
data = [(0.0, Vectors.dense(0.5, 10.0)),
        (0.0, Vectors.dense(1.5, 20.0)),
        (1.0, Vectors.dense(1.5, 30.0)),
        (0.0, Vectors.dense(3.5, 30.0)),
        (0.0, Vectors.dense(3.5, 40.0)),
        (1.0, Vectors.dense(3.5, 40.0))]
df = spark.createDataFrame(data,['labels','features'])


In [ ]:
r = ChiSquareTest.test(df, "features", "labels")

r.collect()

p valuesColumn<'pValues'>
Out[68]: [Row(pValues=DenseVector([0.6873, 0.6823]), degreesOfFreedom=[2, 3], statistics=DenseVector([0.75, 1.5]))]

In [ ]:
from pyspark.context import SparkContext
sc = SparkContext.getOrCreate()
from pyspark.mllib.random import RandomRDDs
rrdd = RandomRDDs.normalRDD(sc,1000000,10)
res = rrdd.map(lambda x : 1.0+2.0*x)
res.collect()

Out[74]: [-1.5444960849135558,
 1.8545650164379217,
 0.09022758533986797,
 -1.0486594100797273,
 -2.559126361887351,
 -1.791855613918619,
 6.3245456046884545,
 0.6509785712781302,
 -0.38979240507492197,
 2.3096944149750946,
 0.7528707752784121,
 3.5565464775107363,
 -1.3844229327055992,
 -0.3451600585048036,
 1.9814253033991023,
 1.4751256676484543,
 1.1013093744258389,
 4.956437630362322,
 0.20912455176076739,
 1.231359758982386,
 2.8508453548404686,
 3.1115952606376758,
 0.35017976091125436,
 -0.2988904730063944,
 3.978547173048084,
 -2.193465866342659,
 0.8154574631301795,
 2.095957403198539,
 3.329766816673781,
 0.28418693120298766,
 0.166343296117464,
 2.010847543127606,
 -2.4860003731585896,
 0.5393846258894552,
 -1.8331348655785655,
 2.8732595990349137,
 2.9416002317691934,
 3.3074738114083813,
 3.0261473280163473,
 2.2756773014087313,
 5.755382649972234,
 4.139114364124212,
 -0.9285003672740679,
 2.8540554472704383,
 -2.736050799037985,
 -1.4661007121346188,
 1.4125573427996887

In [ ]:
from pyspark.ml import Pipeline
from pyspark.ml.classification import LogisticRegression
from pyspark.ml.feature import HashingTF,Tokenizer

df = spark.createDataFrame([(0, "a b c d e spark", 1.0),
    (1, "b d", 0.0),
    (2, "spark f g h", 1.0),
    (3, "hadoop mapreduce", 0.0)
], ["id", "text", "label"])
df.collect()

Out[75]: [Row(id=0, text='a b c d e spark', label=1.0),
 Row(id=1, text='b d', label=0.0),
 Row(id=2, text='spark f g h', label=1.0),
 Row(id=3, text='hadoop mapreduce', label=0.0)]

In [ ]:
tokenize = Tokenizer(inputCol='text',outputCol='labels')
hashtf = HashingTF(inputCol=tokenize.getOutputCol(),outputCol="features")

In [ ]:
#applying LR
LR = LogisticRegression(maxIter=10,regParam=0.001)
pipeline =Pipeline(stages = [tokenize,hashtf,LR])
model =pipeline.fit(df)


In [ ]:
#testing the data
test = spark.createDataFrame([
    (4, "spark i j k"),
    (5, "l m n"),
    (6, "spark hadoop spark"),
    (7, "apache hadoop")
], ["id", "text"])
pred = model.transform(test)
pred.collect()

Out[83]: [Row(id=4, text='spark i j k', labels=['spark', 'i', 'j', 'k'], features=SparseVector(262144, {19036: 1.0, 68693: 1.0, 173558: 1.0, 213660: 1.0}), rawPrediction=DenseVector([0.5288, -0.5288]), probability=DenseVector([0.6292, 0.3708]), prediction=0.0),
 Row(id=5, text='l m n', labels=['l', 'm', 'n'], features=SparseVector(262144, {1303: 1.0, 52644: 1.0, 248090: 1.0}), rawPrediction=DenseVector([4.1691, -4.1691]), probability=DenseVector([0.9848, 0.0152]), prediction=0.0),
 Row(id=6, text='spark hadoop spark', labels=['spark', 'hadoop', 'spark'], features=SparseVector(262144, {173558: 2.0, 198017: 1.0}), rawPrediction=DenseVector([-1.865, 1.865]), probability=DenseVector([0.1341, 0.8659]), prediction=1.0),
 Row(id=7, text='apache hadoop', labels=['apache', 'hadoop'], features=SparseVector(262144, {68303: 1.0, 198017: 1.0}), rawPrediction=DenseVector([5.4156, -5.4156]), probability=DenseVector([0.9956, 0.0044]), prediction=0.0)]

In [ ]:
selected = pred.select("id", "text", "probability", "prediction")
selected.collect()
for i in selected.collect():
    rid, text, prob, prediction = i
    print("(%d, %s) --> prob=%s, prediction=%f" % (rid, text, str(prob), prediction))


(4, spark i j k) --> prob=[0.6292098489668488,0.37079015103315116], prediction=0.000000
(5, l m n) --> prob=[0.984770006762304,0.015229993237696027], prediction=0.000000
(6, spark hadoop spark) --> prob=[0.13412348342566147,0.8658765165743385], prediction=1.000000
(7, apache hadoop) --> prob=[0.9955732114398529,0.00442678856014711], prediction=0.000000
